CREATE TABLE URUN_KATEGORI(
ID INT IDENTITY PRIMARY KEY,
KATEGORI_AD NVARCHAR(50) NOT NULL,
)

CREATE TABLE MUSTERILER(
ID INT IDENTITY PRIMARY KEY,
AD NVARCHAR(50) NOT NULL,
SOYAD NVARCHAR(50) NOT NULL,
TEL1 NVARCHAR(20) NOT NULL,
TEL2 NVARCHAR(20),
MESLEK NVARCHAR(20) NOT NULL,
)

CREATE TABLE ADRES(
ID INT IDENTITY PRIMARY KEY,
ADRES NVARCHAR(250) NOT NULL,
MUSTERI_ID INT NOT NULL,
CONSTRAINT FK_MUSTERI_ADRES FOREIGN KEY (MUSTERI_ID) REFERENCES MUSTERILER(ID)
)

CREATE TABLE URUN(
ID INT IDENTITY PRIMARY KEY,
AD NVARCHAR(50) NOT NULL,
MARKA NVARCHAR(50) NOT NULL,
ADET SMALLINT NOT NULL,
ALIS_FIYAT DECIMAL(18,2) NOT NULL,
SATIS_FIYAT DECIMAL(18,2) NOT NULL,
KATEGORI_ID INT NOT NULL
CONSTRAINT FK_URUN_URUNKATEGORI FOREIGN KEY (KATEGORI_ID) REFERENCES URUN_KATEGORI(ID),
)

CREATE TABLE SIPARIS(
ID INT IDENTITY PRIMARY KEY,
MUSTERI_ID INT NOT NULL,
URUN_ID INT NOT NULL,
SIPARIS_DURUM CHAR NOT NULL, --H:Hazýrlanýyor K:Kargoda T:Teslim Edildi
DETAY NVARCHAR(250) NULL
CONSTRAINT FK_URUN_SIPARIS FOREIGN KEY (URUN_ID) REFERENCES URUN(ID),
CONSTRAINT FK_MUSTERI_SIPARIS FOREIGN KEY (MUSTERI_ID) REFERENCES MUSTERILER(ID)
)

INSERT INTO URUN_KATEGORI VALUES ('BEYAZ EÞYA');
INSERT INTO URUN_KATEGORI VALUES ('DEKORASYON');
INSERT INTO URUN_KATEGORI VALUES ('ELEKTRONÝK');

INSERT INTO URUN VALUES ('PC','LENOVO',23,1250,2500,3);
INSERT INTO URUN VALUES ('BUZDOLABI','VESTEL',10,3200,5000,1);
INSERT INTO URUN VALUES ('ÇAMAÞIR MAKÝNASI','BOSCH',13,2300,3150,1);

INSERT INTO ADRES VALUES ('ADRES1',1);
INSERT INTO ADRES VALUES ('ADRES2',1);
INSERT INTO ADRES VALUES ('ADRES3',2);

INSERT INTO MUSTERILER VALUES ('AHMET', 'YILMAZ', '05355553322', NULL, 'ÖÐRETMEN');
INSERT INTO MUSTERILER VALUES ('MEHMET', 'AKPINAR', '05324724265', NULL, 'ÖZEL SEKTÖR');
INSERT INTO MUSTERILER VALUES ('YUSUF', 'HALDIZ', '05327654321', NULL, 'POLÝS');

INSERT INTO SIPARIS VALUES (1,1,'H','LENOVO ÝDEAPAD320 Ý5 7TH GEN');
INSERT INTO SIPARIS VALUES (3,2,'K','VESTEL BUZDOLOBI 2019');

